# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Jellyfin Plugin Manager

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    - name: Cat out assets json file
      run: cat obj/project.assets.json
    - name: jprm-build
      uses: oddstr13/jellyfin-plugin-repository-manager@v1.1.1
    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: custom-tabs-zip
        path: ./artifacts/custom-tabs_0.2.8.1.zip
    - name: Create release
      uses: softprops/action-gh-release@v6
      with:
        files: ./artifacts/custom-tabs_0.2.8.1.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
